services:
  # asr:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001"
  # depends_on:
  #   elastic-backend:
  #     condition: service_healthy
  #     restart: true
  elastic-backend:
    image: elasticsearch:8.17.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    volumes:
      - ./data:/usr/data
      - ./elastic-backend:/usr/elastic-backend
    # command: bash -c "./bin/elasticsearch && /usr/elastic-backend/setup.sh"
    # command: ./bin/elasticsearch && /usr/elastic-backend/setup.sh
    # command: /usr/elastic-backend/setup.sh

volumes:
  data:
    external: true
  elastic-backend:
